# Generated by Django 4.0.5 on 2022-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cellphone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_intention',
            field=models.TextField(default=''),
        ),
    ]
