# Generated by Django 4.0.5 on 2022-12-18 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('INITIAL', 'Initial'), ('ASK_NAME', 'Ask Name'), ('ASK_SUMMARY', 'Ask Summary'), ('ASK_WIN', 'Ask Win'), ('ASK_IMPROVEMENT', 'Ask Improvement'), ('FINISHED', 'Finished')], default='INITIAL', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
