# Generated by Django 4.0.5 on 2022-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='state',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('ASK_NAME', 'Ask Name'), ('ASK_JOURNAL_START', 'Ask Journal Start'), ('ASK_SUMMARY', 'Ask Summary'), ('ASK_WIN', 'Ask Win'), ('ASK_IMPROVEMENT', 'Ask Improvement'), ('FINISHED', 'Finished')], default='INITIAL', max_length=20),
        ),
    ]
